#!/usr/bin/env bash
# Mesh Canary installer.
# Creates a virtual environment, installs dependencies, and generates a
# run-node.sh wrapper so starting a node is a single command.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"

echo "==> Mesh Canary installer"

if ! command -v python3 &>/dev/null; then
  echo "Error: python3 not found. Install Python 3.9+ first." >&2
  exit 1
fi

PYVER="$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')"
echo "==> Found python3 ($PYVER)"

echo "==> Creating virtual environment in .venv"
python3 -m venv "$VENV_DIR"

echo "==> Installing dependencies"
"$VENV_DIR/bin/pip" install --upgrade pip --quiet
"$VENV_DIR/bin/pip" install cryptography --quiet

mkdir -p "$PROJECT_DIR/data"

if [ ! -f "$PROJECT_DIR/peers.json" ]; then
  cp "$PROJECT_DIR/peers.json.example" "$PROJECT_DIR/peers.json"
  echo "==> Создан peers.json из шаблона — впиши хотя бы один bootstrap-адрес перед запуском"
fi

if [ ! -f "$PROJECT_DIR/targets.json" ]; then
  cp "$PROJECT_DIR/targets.json.example" "$PROJECT_DIR/targets.json"
  echo "==> Создан targets.json из шаблона"
fi

cat > "$PROJECT_DIR/run-node.sh" << 'RUNNER'
#!/usr/bin/env bash
# Convenience wrapper generated by install.sh — edit env vars below or
# export them before running, e.g.:
#   MESHCANARY_ADVERTISE_HOST=1.2.3.4 ./run-node.sh
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PORT="${MESHCANARY_PORT:-9001}"
WEB_PORT="${MESHCANARY_WEB_PORT:-8080}"

ARGS=(
  --port "$PORT"
  --id-file "$DIR/data/node.key"
  --db "$DIR/data/node.db"
  --targets "$DIR/targets.json"
  --peers "$DIR/peers.json"
  --web-port "$WEB_PORT"
)

if [ -n "${MESHCANARY_ADVERTISE_HOST:-}" ]; then
  ARGS+=(--advertise-host "$MESHCANARY_ADVERTISE_HOST")
fi

exec "$DIR/.venv/bin/python3" "$DIR/node.py" "${ARGS[@]}" "$@"
RUNNER
chmod +x "$PROJECT_DIR/run-node.sh"

echo
echo "==> Done."
echo "    1. Add at least one bootstrap peer to peers.json"
echo "       e.g. {\"peers\": [{\"host\": \"some.friend.example\", \"port\": 9001}]}"
echo "    2. Run:  ./run-node.sh"
echo "    3. Dashboard: http://localhost:8080"
